CREATE TABLE Users
(
    USER_ID             VARCHAR(255) PRIMARY KEY,
    USERNAME            VARCHAR(50)  NOT NULL,
    PROFILE_IMAGE       VARCHAR(255),
    PASSWORD            VARCHAR(255) NOT NULL,
    EMAIL               VARCHAR(100) NOT NULL UNIQUE,
    PROFILE_DESCRIPTION VARCHAR(500),
    ROLE                VARCHAR(50) DEFAULT 'User',
    CREATED_BY          VARCHAR(255) NOT NULL,
    CREATED_AT          TIMESTAMP,
    UPDATED_BY          VARCHAR(255),
    UPDATED_AT          TIMESTAMP
);

CREATE TABLE Anime
(
    ANIME_ID           VARCHAR(255) PRIMARY KEY,
    ANIME_NAME         VARCHAR(255),
    ANIME_NAME_JP      VARCHAR(255),
    ANIME_PV_URL       VARCHAR(500),
    ANIME_IMAGE        VARCHAR(500),
    ANIME_POSTER       VARCHAR(500),
    ANIME_DESCRIPTION  TEXT,
    ANIME_RATING       DECIMAL,
    ANIME_RELEASE_DATE TIMESTAMP,
    ANIME_VIEWS        INT,
    ANIME_STATUS       VARCHAR(50),
    GENRE_ID           VARCHAR(255),
    STUDIO_ID          VARCHAR(255),
    SEASON             VARCHAR(50),
    CHARACTER_ID       VARCHAR(255),
    CREATED_BY         VARCHAR(255) NOT NULL,
    CREATED_AT         TIMESTAMP,
    UPDATED_BY         VARCHAR(255),
    UPDATED_AT         TIMESTAMP
);

CREATE TABLE GENRES
(
    GENRE_ID   VARCHAR(255) PRIMARY KEY,
    GENRE_NAME VARCHAR(255),
    CREATED_BY VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP,
    UPDATED_BY VARCHAR(255),
    UPDATED_AT TIMESTAMP
);

CREATE TABLE CHARACTERS
(
    CHARACTER_ID    VARCHAR(255) PRIMARY KEY,
    CHARACTER_NAME  VARCHAR(255) NOT NULL,
    CHARACTER_IMAGE VARCHAR(500),
    ANIME_ID        VARCHAR(255),
    CREATED_BY      VARCHAR(255) NOT NULL,
    CREATED_AT      TIMESTAMP,
    UPDATED_BY      VARCHAR(255),
    UPDATED_AT      TIMESTAMP
);

CREATE TABLE VOICE_ACTORS
(
    VA_ID        VARCHAR(255) PRIMARY KEY,
    VA_NAME      VARCHAR(255) NOT NULL,
    VA_IMAGE     VARCHAR(500),
    VA_BIRTHDATE DATE,
    CREATED_BY   VARCHAR(255) NOT NULL,
    CREATED_AT   TIMESTAMP,
    UPDATED_BY   VARCHAR(255),
    UPDATED_AT   TIMESTAMP
);

CREATE TABLE STUDIO
(
    STUDIO_ID   VARCHAR(255) PRIMARY KEY,
    STUDIO_NAME VARCHAR(255) NOT NULL UNIQUE,
    COUNTRY     VARCHAR(100),
    STUDIO_LOGO VARCHAR(500),
    WEBSITE     VARCHAR(500),
    CREATED_BY  VARCHAR(255) NOT NULL,
    CREATED_AT  TIMESTAMP,
    UPDATED_BY  VARCHAR(255),
    UPDATED_AT  TIMESTAMP
);
